### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by ankitshubham97** [authorjapps/zerocode-hello-world#17]
I git cloned the repo:

> git clone https://github.com/authorjapps/zerocode-hello-world.git

I cd into zerocode-hello-world:

> cd zerocode-hello-world/

I did a clean build:

> ./gradlew clean build

It threw following error:

> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

On googling, I found this StackOverflow link: https://stackoverflow.com/a/44782145/5657783. I tried the following based on the answer and then it worked:

> Ankits-MacBook-Air:zerocode-hello-world-fork ankitshubham$ gradle wrapper
> 
> BUILD SUCCESSFUL in 857ms
> 1 actionable task: 1 executed
> Ankits-MacBook-Air:zerocode-hello-world-fork ankitshubham$ git reset --hard
> HEAD is now at bf6f651 Merge pull request #15 from authorjapps/ISS-229
> Ankits-MacBook-Air:zerocode-hello-world-fork ankitshubham$ ./gradlew clean build
> <Executed>

How to fix this? Or should we put something on this line in the README?

**Comment by authorjapps** [comment]
@ankitshubham97 , that's great. Thanks for the PR.

We will review n merge this soon.

**Comment by authorjapps** [comment]
PR has been approved n merged now.

Can you close both issues please? 👍

**Comment by nirmalchandra** [comment]
PR https://github.com/authorjapps/zerocode/pull/285 has been raised to solve this issue.

Note- 
This is not a Zerocode issue, it's a JayWay Jaon Path issue (or a natural behavior when it comes to finding a matching element - The match could be one or more, hence an array is returned always). 

Now, Zerocode has provided a solution to pick the field value from the `JsonPath matching` result array so that automation testers are unblocked when they face this kind of situation.

**Comment by authorjapps** [comment]
Thanks @ankitshubham97 for this.
CI build has passed.

Can you please close the ticket(s)?
